#!/bin/sh
logger "test this thing"

sleep 2

${pkgs.sudo}/bin/sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 ${pkgs.pulseaudio}/bin/pactl set-card-profile bluez_card.CC_98_8B_D2_0D_71 handsfree_head_unit

logger "test log to syslog"